apiVersion: v1
data:
  master-datasources.xml: |
    <datasource>
        <name>WarehouseDB</name>
        <description>The datasource used for config registry</description>
        <jndiConfig>
            <name>jdbc/WarehouseDB</name>
            </jndiConfig>
            <definition type="RDBMS">
                <configuration>
                    <url>jdbc:mysql://mysql:3306/warehouse?autoReconnect=true&amp;useSSL=false</url>
                    <username>wso2carbon</username>
                    <password>wso2carbon</password>
                    <driverClassName>com.mysql.jdbc.Driver</driverClassName>
                    <maxActive>80</maxActive>
                    <maxWait>60000</maxWait>
                    <testOnBorrow>true</testOnBorrow>
                    <validationQuery>SELECT 1</validationQuery>
                    <validationInterval>30000</validationInterval>
                </configuration>
            </definition>
    </datasource>
kind: ConfigMap
metadata:
  name: integrator-conf-datasources
  namespace: "k8swso2demo"
---
